# Kausalsammenheng

Med statistiske verktøy kan vi estimere sammenhenger mellom variabler. For eksempel kan en t-test brukes for å si noe om forskjellen mellom to grupper, vi kan se på dette som en mulig sammenheng mellom gruppe og en utfallsvariabel. På en lignende måte kan en inndeling i flere grupper ha en sammenheng med en utfallsvariabel, noe som kan måles ved hjelp av en ANOVA-modell. En mer generell statistisk modell er regresjonsmodellen. Ved bruk av en regresjonsmodell kan vi måle sammenhengen mellom en eller flere uavhengige variabler og en avhengig variabel. Statistikken er full av modeller og metoder som måler sammenhenger.

Men hvordan kan vi tolke sammenhenger? I vitenskapshistorien finnes flere eksempler på hvordan man argumenterer for at vi ikke kan si noe om en kausalsammenheng basert på en statistisk sammenheng. «Correlation does not imply causation» er en vanlig frase som brukes for å avferda sammenhenger som betydningsløse. Vi kan finne støtte for en slik forståelse, hver morgen (i hvert fall på en hverdag, og i hvert fall om høsten) når vekkerklokken din ringer står du opp og lager en kopp kaffe. Når du setter deg ned for å drikke kaffen stiger solen over horisonten. Men, det at du drikker kaffe får ikke solen til å gå opp. Her finnes ingen kausalsammenheng.

