<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Statistisk dataanalyse med Jamovi - 10&nbsp; En arbeidsflyt for statistisk analyse i Jamovi</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./05-jamovi.html" rel="next">
<link href="./05-a-intro.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating slimcontent">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./05-a-intro.html">Presentere og lese statistiske analyser</a></li><li class="breadcrumb-item"><a href="./05-formidling.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">En arbeidsflyt for statistisk analyse i Jamovi</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistisk dataanalyse med Jamovi</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Forord</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01-a-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deskriptiv dataanalyse</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-deskriptiv-dataanalyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Datahåndtering og Data i regnearkprogrammer</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01-jamovi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Deskriptiv dataanalyse i Jamovi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02-a-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Statistisk samvariasjon</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-statistisk-samvariasjon.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Statistisk samvariasjon i dataanalyse</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02-jamovi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Statistiske metoder for samvariasjon i Jamovi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03-a-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Kausalsammenheng</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-kausalsammenheng.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Fra sammenheng til kausalitet</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-jamovi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Kausal analyse i Jamovi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03-kausal-ressurs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Kausalsammenhenger læringsressurser</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./04-a-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Induktiv statistikk</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-induktiv-statistikk.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Statistisk inferens</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04-jamovi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Statistisk inferens i Jamovi</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./05-a-intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentere og lese statistiske analyser</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-formidling.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">En arbeidsflyt for statistisk analyse i Jamovi</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05-jamovi.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">05-jamovi.html</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Referanser</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Innhold</h2>
   
  <ul>
  <li><a href="#rådata-og-bearbeidet-data" id="toc-rådata-og-bearbeidet-data" class="nav-link active" data-scroll-target="#rådata-og-bearbeidet-data"><span class="header-section-number">10.0.1</span> Rådata og bearbeidet data</a></li>
  <li><a href="#analysefiler" id="toc-analysefiler" class="nav-link" data-scroll-target="#analysefiler"><span class="header-section-number">10.0.2</span> Analysefiler</a></li>
  <li><a href="#rapporter-og-figurer" id="toc-rapporter-og-figurer" class="nav-link" data-scroll-target="#rapporter-og-figurer"><span class="header-section-number">10.0.3</span> Rapporter og figurer</a></li>
  <li><a href="#les-meg" id="toc-les-meg" class="nav-link" data-scroll-target="#les-meg"><span class="header-section-number">10.0.4</span> Les-meg!</a></li>
  <li><a href="#presentere-statistiske-analyser" id="toc-presentere-statistiske-analyser" class="nav-link" data-scroll-target="#presentere-statistiske-analyser"><span class="header-section-number">10.1</span> Presentere statistiske analyser</a></li>
  <li><a href="#beskrive-analyser-i-metode" id="toc-beskrive-analyser-i-metode" class="nav-link" data-scroll-target="#beskrive-analyser-i-metode"><span class="header-section-number">10.2</span> Beskrive analyser i metode</a></li>
  <li><a href="#lese-statistiske-analyser" id="toc-lese-statistiske-analyser" class="nav-link" data-scroll-target="#lese-statistiske-analyser"><span class="header-section-number">10.3</span> Lese statistiske analyser</a></li>
  <li><a href="#vitenskapelige-skriving-en-strukturert-rapport" id="toc-vitenskapelige-skriving-en-strukturert-rapport" class="nav-link" data-scroll-target="#vitenskapelige-skriving-en-strukturert-rapport"><span class="header-section-number">10.4</span> Vitenskapelige skriving: En strukturert rapport</a>
  <ul class="collapse">
  <li><a href="#introduksjon" id="toc-introduksjon" class="nav-link" data-scroll-target="#introduksjon"><span class="header-section-number">10.4.1</span> Introduksjon</a></li>
  <li><a href="#metode" id="toc-metode" class="nav-link" data-scroll-target="#metode"><span class="header-section-number">10.4.2</span> Metode</a></li>
  <li><a href="#resultat" id="toc-resultat" class="nav-link" data-scroll-target="#resultat"><span class="header-section-number">10.4.3</span> Resultat</a></li>
  <li><a href="#diskusjon" id="toc-diskusjon" class="nav-link" data-scroll-target="#diskusjon"><span class="header-section-number">10.4.4</span> Diskusjon</a></li>
  </ul></li>
  <li><a href="#paragrafer" id="toc-paragrafer" class="nav-link" data-scroll-target="#paragrafer"><span class="header-section-number">10.5</span> Paragrafer</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">En arbeidsflyt for statistisk analyse i Jamovi</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<p>Vi har allerede snakket om hvordan et analyseprosjekt kan organiseres i den første modulen så utgangspunktet for diskusjonen her blir en repetisjon. Et analyseprosjekt bør være <strong>reproduserbart</strong>, dette betyr at all informasjon som kreves for å gjenskape analyseresultatene bør finnes sammen med den rapport du lager. Prosjektet du arbeider på bør også være <strong>transparent</strong> noe som gjør at det bør følge med detaljerte beskrivninger av hvorfor og hvordan man valgt å lage analysen på en gitt måte.</p>
<p>Vi løser begge disse kravene ved å skape en struktur for dataanalysen. I notatene fra den første modulen leser vi at vi lager analysen som en isolert mappe. Denne mappen inneholder alle deler som kreves for å lese en reproduserbar og transparent analyse, rapporten er bare en del. I rapporten er det fullt mulig at du ikke har plass till å beskrive hele din analyse. Men i mappen så bør disse beskrivelser være med. I din analysemappe finner vi:</p>
<ul>
<li>Rådata: Data som er urørt etter det at man matet inn eller innhentet den i forskjellige programmer osv.</li>
<li>Delvis bearbeidet data: Data som er organisert for data analyse</li>
<li>Analysefiler: Filer som er kan lese til eks. Jamovi og inneholder analyser av din data</li>
<li>Rapporter og figurer: Disse er sluttprodukter av deres arbeid, disse kan settes sammen til eks. en bachelor-oppgave.</li>
</ul>
<section id="rådata-og-bearbeidet-data" class="level3" data-number="10.0.1">
<h3 data-number="10.0.1" class="anchored" data-anchor-id="rådata-og-bearbeidet-data"><span class="header-section-number">10.0.1</span> Rådata og bearbeidet data</h3>
<p>Når bearbeiding av rådata skjer manuelt bør du ha rådata lagret. Dette gir muligheter for å finne frem mulige feil ved senere anledning. Bearbeidet data kan være data hvor rad og kolonne i et excelark har blitt bearbeidet for å passe import til jamovi eller hvor gjennomsnitt fra flere filer har blitt lagt inn et samlet ark.</p>
</section>
<section id="analysefiler" class="level3" data-number="10.0.2">
<h3 data-number="10.0.2" class="anchored" data-anchor-id="analysefiler"><span class="header-section-number">10.0.2</span> Analysefiler</h3>
<p>I jamovi er det mulig å spare analysefiler som inneholder data og statistiske analyser. Hvis du bruker et datasett for flere analyser finnes det en risiko for at analysefilene krever mye av din PC. Det er da en god ide å bruke flere forskjellige analysefiler for bestemte underanalyser.</p>
<p>Et eksempel på en sånn oppdeling kan være at en første analysefil inneholder deskriptiv analyse av datasettet. Vi navngir denne filen med et beskrivende navn, eksempelvis <strong>deskriptiv-data-analyse.omv</strong>. Her begrenser vi oss til å skape en tabell som beskriver variabler i datasettet som i sin tur beskriver vårt utvalg. I en den neste filen bruker vi statistisk inferens får å besvare problemstillingen i studien, for eksempel, hvilken treningsmodell er best for å utvikle styrke. Denne analysen bygger på sammenligninger, vi navngir file <strong>sammenligninger-grupper-analyse.omv</strong>. I en siste fil lager vi noen figurer og</p>
</section>
<section id="rapporter-og-figurer" class="level3" data-number="10.0.3">
<h3 data-number="10.0.3" class="anchored" data-anchor-id="rapporter-og-figurer"><span class="header-section-number">10.0.3</span> Rapporter og figurer</h3>
<p>En rapport kan være i formen av en BA-oppgave eller en presentasjon. Når rapporten er et dokument som fremst skal leses bør den skrives deretter. Vi har tidligere snakket om dette, hvis du ønsker å lese dette igjen finner du teksten gjengitt her under.</p>
<p>For å gi større muligheter til å forandre deler i rapporten bør figurer og tabeller holdes adskilte helt til rapporten skal settes sammen for innlevering eller publisering. Lag figurer som separate filer (se under for et forslag på arbeidsflyt). Lag tabeller i et eget dokument.</p>
<section id="et-arbeidsflyt-for-å-lage-figurer-i-jamovi" class="level4" data-number="10.0.3.1">
<h4 data-number="10.0.3.1" class="anchored" data-anchor-id="et-arbeidsflyt-for-å-lage-figurer-i-jamovi"><span class="header-section-number">10.0.3.1</span> Et arbeidsflyt for å lage figurer i Jamovi</h4>
<p>Jamovi har flere muligheter for å lage figurer. Men jamovi er begrenset når det kommer til å tilpasse figurer. Får å lage forandre elementer i en figur kan vi bruke f.eks. power-point og legge til tekst, forandre aksler eller farger osv. Her under følger en kort et eksempel:</p>
<ol type="1">
<li>Lag figuren i Jamovi. Her har du flere alternativer: Under “exploration” kan vi lage figurer som beskriver data basert på grupperinger og gjennomsnitt. Vi kan og laste inn nye moduler så som Flexplot og jjStatsPlot. Disse modulene har en bedre muligheter for å lage figurer. Når vi vel har laget en figur kan vi …</li>
<li>Eksportere figurelementer. Dette kan gjøres ved å høyreklikk på figuren og velge copy i menyen som heter Image. Når du så limer inn i for eksempel power-point limer du inn en PNG-fil. Denne filen har noe lavere kvalitet. Hvis du istedenfor velger å eksportere som .SVG får du høyere kvalitet. Dra figuren (som du lagrer på din PC) inn i et nytt lysbilde i power point.</li>
<li>Du kan nå velge å lage egne akseltekster, legge til forklarende tekst osv. Hvis du ønsker å ta vekk eller forandre deler av bildet kan du velge ved høyreklikk Grupper og Del opp gruppe. Denne operasjonen gir deg full kontroll over alle delene i grafen. Dessverre forsvinner teksten, du må legge inn den på nytt.</li>
<li>Du har nå mulighet å lage en figur med flere paneler, noe som vil imponere sensorer!</li>
<li>Endre størrelse. Før du er helt klar er det lurt å eksportere figuren i den størrelsen som du ønsker i rapporten. En kolonne med text i word har 16.51 cm bredde og ca 22 cm høyde. Hvis du lager en figur som holder seg innenfor disse målene blir dokumentet lettere o formattere. Under Utforming, velg Lysbildestørrelse og endre til ønsket størrelse.</li>
<li>Eksporter figur. Fra power-point kan du eksportere figuren som flere formater. Du har mulighet å eksportere bilder som tiff-filer, disse vil ha høy kvalitet. Under Fil &gt; Eksporter, velg Endre filtype, trykk på Andre Filtyper og trykk på Lagre som. I neste meny, velg .tif under filtype.</li>
<li>Lim inn i word ved å dra bildefilen til word-dokumentet.</li>
</ol>
<p>Hvis man ønsker enda mer kontroll for å redigere figurer kan en .svg-fil redigeres i <a href="https://inkscape.org/">Inkscape</a></p>
</section>
</section>
<section id="les-meg" class="level3" data-number="10.0.4">
<h3 data-number="10.0.4" class="anchored" data-anchor-id="les-meg"><span class="header-section-number">10.0.4</span> Les-meg!</h3>
<p>Vi finner også en README-fil. Denne bør skrives i et format som kan leses av flest mulig, dette betyr at et word-dokument er på grensen da alle ikke har installert programvare som kan lese word. Et bedre alternativ er en .txt-fil. I README.txt kan vi beskrive prosjektet:</p>
<pre><code>
## Tittel på prosjektet
Her under følger et kort sammendrag av prosjektets bakgrunn, problemstilling, metode og konklusjoner. Det er ikke tanken at all informasjon finnes her men at leseren gis kontekst til hva som følger.

## Innhold i analysen
Her under beskriver vi de filer og datasett som blir brukt i analysene. Beskrivelsene kan struktureres under de undermapper som de finnes i.

- /data
    - datasett-01-deskriptiv-data.xlsx
    - datasett-02-gruppesammenligninger.xlsx
- /rådata
    - fil1-testdag1.xlsx
    - ...
- /analyse
    - deskriptiv-data-analyse.omv
- rapport.docx
- /figurer
    - ...

Hver fil eller datasett kan beskrives i detalj under.

</code></pre>
</section>
<section id="presentere-statistiske-analyser" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="presentere-statistiske-analyser"><span class="header-section-number">10.1</span> Presentere statistiske analyser</h2>
<p>En statistisk analyse bør presenteres til ditt publikum på en måte som gjør det klart hva din hensikt med presentasjonen er. Vi har i dette emnet forenklet snakket om presentasjoner som er deskriptive (beskrivende) og som har som hensikt å trekke slutninger om en populasjon basert på et utvalg (statistisk inferens). Vi kan legge til to kategorier her for en mer detaljert syn på statistisk inferens:</p>
<ul>
<li>En analyse kan bygge på hypotesetesting. En problemstilling formuleres i forkant av analysearbeidet, den statistiske analysen gir støtte eller forkaster en nullhypotese.</li>
<li>En analyse kan være eksplorativ. Vi ønsker fortsatt å si noe om en populasjon basert på et utvalg, problemstillinger kan formuleres i forkant av analysen, men dataene er ikke nødvendigvis innsamlet med denne hensikten i tankene.</li>
</ul>
<p>I begge er det meget viktig å beskrive hva som er <strong>avhengig variabel</strong>, hva er det du ønsker å beskrive eller trekke slutninger om? I tillegg til de variabler som kreves for å angripe din problemstilling finnes det muligens flere variabler som du bruker for å beskrive datasettet, utvalget eller populasjonen. Du bør gjøre det klart for ditt publikum hvordan disse henger sammen og hvorfor de presenteres.</p>
<p>Det finnes flere guider for hvordan man presenterer statistiske resultater. En meget brukt guide er den som publiseres av American Psychological Association (APA), en forkortet versjon finner dere <a href="https://apastyle.apa.org/instructional-aids/numbers-statistics-guide.pdf">her</a>. Å følge en guide kan gi fordeler, men du bør også tenke på hva du ønsker å formidle. I eksemplet under beskriver vi forskjellen mellom grupper i utvalget og hva vi tror om forskjellen mellom grupper i populasjonen.</p>
<blockquote class="blockquote">
<p>SI oppviste en økning i VO<sub>2maks</sub> som var 281 ml <span class="math inline">\(\times\)</span> min<sup>-1</sup> større enn LI (95% KI: [53, 507], <em>t</em><sub>(15)</sub> = 2.64, <em>p</em> = 0.019).</p>
</blockquote>
<p>Vi presenterer altså beskrivende statistikk hva gjelder utvalget sammen med konfidensintervaller og resultatet fra en t-test som gir en indikasjon på hva vi tror om gjennomsnittet i populasjonen ( konfidensintervall) og hvor sannsynlig det observerte resultatet eller et enda mer ekstremt resultat er hvis nullhypotesen er sann (<em>t</em> og <em>p</em>-verdier). Vi kan tenke oss å presentere ytterligere statistikker fra testen så som effekt størrelse.</p>
<p>Hvorfor presentere <em>t</em> sammen med <em>p</em>? Vi ønsker å vise at vi er å stole på, en gitt <em>t</em>-verdi bør samsvare med en <em>p</em>-verdi. Se f.eks. <a href="http://courses.atlas.illinois.edu/spring2016/STAT/STAT200/pt.html">her for en kalkulator for <em>t</em> og <em>p</em></a>. En annen hensikt er å vise effekten i testen i standardiserte enheter, <em>t</em>-verdien beregnes som gjennomsnittlig forskjell delt på standardfeilen for forskjellen (<span class="math inline">\(t = \frac{x_1 - x_2}{SE(x_1 - x_2)}\)</span>). Vi får altså vite hvor mange standardfeil som skiller to gjennomsnitt. Vi ser også retningen på effekten (negativ eller positiv).</p>
<p>Når vi presenterer resultater fra statistiske tester som er mer avanserte kan en tabell hjelpe. En regresjonstabell gir oss all informasjon som kreves for å presentere resultater. Legg merke til at Thrane presenterer en noe forenklet tabell. En regresjonstabell fra jamovi inneholder flere elementer som kan bidra til tolking av resultatene. En noe mer avansert modell for sammenligning av VO<sub>2maks</sub> etter en intervensjon som ble presentert som en t-test på differenser over kan være en ANCOVA modell. ANCOVA står for Analysis of Co-Variance. Her analyseres en kontinuerlig variabel som avhengig variabel sammen med en kategorisk variabel og kontinuerlig variabel som uavhengig variabel. Målet er å estimere forskjell i verdier post-intervensjon når vi kontrollerer for pre-intervensjons verdier. I tabellen under presentere resultater fra denne analysen.</p>
<table class="table">
<colgroup>
<col style="width: 37%">
<col style="width: 12%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 7%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Predictor</th>
<th>Estimate</th>
<th>SE</th>
<th>95% CI Lower</th>
<th>95% CI Upper</th>
<th>t</th>
<th>p</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept ᵃ</td>
<td>553.56</td>
<td>562.68</td>
<td>-653.27</td>
<td>1760.39</td>
<td>0.98</td>
<td>0.3419</td>
</tr>
<tr class="even">
<td>pre</td>
<td>0.87</td>
<td>0.11</td>
<td>0.65</td>
<td>1.10</td>
<td>8.23</td>
<td>9.87e-7</td>
</tr>
<tr class="odd">
<td>group:</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
</tr>
<tr class="even">
<td>SI – LI</td>
<td>275.22</td>
<td>104.89</td>
<td>50.25</td>
<td>500.19</td>
<td>2.62</td>
<td>0.0200</td>
</tr>
<tr class="odd">
<td>ᵃ Represents reference level</td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>I fall da vi bare ønsker å gi leseren estimatet vi er interesserte i, forskjell mellom grupper etter intervensjonen, kan vi skrive:</p>
<blockquote class="blockquote">
<p>Etter intervensjonen var VO<sub>2maks</sub> 275 ml <span class="math inline">\(\times\)</span> min<sup>-1</sup> høyere i SI-gruppen sammenlignet med LI når vi kontrollerer for pre-intervensjonsverdier (95% KI: [50, 500], <em>t</em><sub>(14)</sub> = 2.62, <em>p</em> = 0.02, se tabell 2 for en helhetlig regresjonstabell).</p>
</blockquote>
<p>Vi henviser till tabell 2 for en komplett tabell med alle estimatene.</p>
<p>Når du har mulighet, komplettere gjerne dine analyser med en figur. I noen vitenskapelige tidsskrifter kreves det at individuelle datapunkter presenteres i figur når antallet observasjoner per gruppe er lavt. Dette er praksis som gjør rapporter mer transparente. Tenk på at figurer og tekst skal komplettere hverandre, presenter ikke de samme resultatene i en figure som i tekst. Hvis vi skaper en figur som viser forskjell mellom gruppene sammen med et konfidensintervall løfter vi vekk denne informasjonen fra teksten og henviser til figuren.</p>
<blockquote class="blockquote">
<p>Etter intervensjonen var VO<sub>2maks</sub> høyere i SI-gruppen sammenlignet med LI når vi kontrollerer for pre-intervensjonsverdier (se Figur 1, <em>t</em><sub>(14)</sub> = 2.62, <em>p</em> = 0.02, se Tabell 2 for en helhetlig regresjonstabell).</p>
</blockquote>
<p>Et resultatkapittel inneholder som regel ikke noe tolkende utsagn annet en indikasjoner på størrelse og retning på effekter, beskrivende statistikk og resultater fra hypotesetester. Tolkningen legger man som regel inn i diskusjonen. Noen ganger kan det kreves at du hjelper leseren å forstå hva du presenterer, du bør då legge inn en ekstra setning som beskriver for eksempel hva du estimerer.</p>
</section>
<section id="beskrive-analyser-i-metode" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="beskrive-analyser-i-metode"><span class="header-section-number">10.2</span> Beskrive analyser i metode</h2>
<p>I et metodekapittel avslutter man ofte med å beskrive de metoder som blir brukt for å analysere dataene. Her bør vi beskrive hvert test som presenteres i resultatene. Vi kan gruppere noe ved å si at “differenser mellom pre- og post-intervensjon i VO2maks og sykkelprestasjon ble sammenlignet mellom grupper ved hjelp av uavhengige t-tester”. I neste setning ønsker vi å si noe om hvordan vi presenterer dataene. “Deskriptiv data blir presentert som gjennomsnitt og standardavvik (SD). Gruppesammenligninger presenteres som gjennomsnittlig forskjell, 95% konfidensintervall sammen med <em>t</em> og <em>p</em>-verdier fra t-tester.”</p>
<p>I denne delen av rapporten er det lurt å være så eksplisitt som mulig, si hva du faktisk har gjort og hvordan du faktisk presenterer dataene.</p>
<p>Til sist kan du fint si at “alle resultater, rådata og analysefiler finnes samlet i…”. Og henvise til deres mappe som inneholder deres analysearbeid.</p>
</section>
<section id="lese-statistiske-analyser" class="level2 page-columns page-full" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="lese-statistiske-analyser"><span class="header-section-number">10.3</span> Lese statistiske analyser</h2>
<p>Vi har nå diskutert hvordan vi kan presentere resultater fra et analyseprosjekt. Vi kan bruke de to ledestjernene for å lage analyseprosjekter når vi leser arbeider også. Vi kan prøve å besvare følgende spørsmål: er analysene presenterte på en transparent måte? Kan jeg reprodusere analysene? Hvis svarene er JA på disse to spørsmål kan vi muligens legge mer troverdighet i de resultater som presenteres.</p>
<p>Vi har gjennom emnet diskutert hvordan vi kan lure oss selve med statistiske verktøy. Når resultatene fra en statistisk analyse tolkes og konklusjoner trekkes kreves at vi kan vedlikeholde en kritisk blikk på analysene. Vi kan prøve å besvare spørsmålet hvordan kan forfatterne lurt seg selve her? En analyse kan være både transparent og mulig å reprodusere, men konklusjonene bygger på at man tolket dataene og resultatene feil eller brukt statistiske modeller som ikke gir en riktig bilde av dataene (og verden). Det å tolke statistiske analyser fra denne synsvinkelen krever trening og en kritisk blikk. Thrane <span class="citation" data-cites="thrane_2020">(<a href="references.html#ref-thrane_2020" role="doc-biblioref">2020</a>)</span> gir noen tips som omhandler for eksempel assosiasjon og kausalitet, absolutte og relative effekter og generalisering til forskjellige populasjoner.</p>
<div class="no-row-height column-margin column-container"><div id="ref-thrane_2020" class="csl-entry" role="listitem">
Thrane, Christer. 2020. <em>Statistisk Dataanalyse På 1-2-3</em>. Cappelen Damm.
</div></div></section>
<section id="vitenskapelige-skriving-en-strukturert-rapport" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="vitenskapelige-skriving-en-strukturert-rapport"><span class="header-section-number">10.4</span> Vitenskapelige skriving: En strukturert rapport</h2>
<p>En vitenskapelig rapport skiller seg på flere måter fra hvordan andre tekster skrives. En vitenskapelig rapport ønsker ofte å formidle kunnskap som baserer seg på data eller logikk på en måte som gir leseren den samme forståelsen av et fenomen som forfatteren av rapporten. Det finnes variasjoner av vitenskapelige tekster som for eksempel når forfatteren ønsker å formidle en mening i en vitenskapelig debatt.</p>
<p>Forskere og andre lesere av vitenskapelige tekster (studenter, trenere, helsearbeidere, politiker osv.) har ikke alltid så mye tid, derfor har det utviklet seg måter å strukturere rapporter på som gjører det enkelt å finne hva man søker etter. Disse strukturer skiller seg mellom ulike felt (f.eks. medisin, psykologi, litteraturvitenskap, sosiologi) og mellom ulike publiseringskanaler (f.eks. mellom ulike tidsskrifter). Men man kan se et felles mønster og dette mønster kan beskrives som</p>
<p><strong>IMR(o)D</strong></p>
<p>Som står for: Introduksjon, Metode, Resultat og Diskusjon.</p>
<p>Denne strukturen er mye brukt i forskningsrapporter som formidler et eksperiment eller observasjoner. Men vi kan og bruke modellen når vi formidler oversikter over et felt gjennom en litteraturoversikt. I noen situasjoner er noen deler ikke nødvendige, for eksempel, når vi rapporterer et enkelt eksperiment med lite plass for tolking kan diskusjonen bli en mindre del eller forsvinne helt. Når vi skriver en tekst til et seminarium kan vi ta vekk metodedelen og resultatene og derved introdusere leseren til et felt følget av en diskusjon om feltet.</p>
<section id="introduksjon" class="level3" data-number="10.4.1">
<h3 data-number="10.4.1" class="anchored" data-anchor-id="introduksjon"><span class="header-section-number">10.4.1</span> Introduksjon</h3>
<p>Hensikten med introduksjonen er å introdusere leseren til den resterende teksten. Vi skal her presentere noen fakta som er viktige for å sette resten av rapporten i en kontekst. Disse fakta bakkes opp av referanser/kilder som presenterer tidligere kunnskap for leseren. Denne første delen av introduksjonen kan sies være deskriptiv, eller beskrivende.</p>
<p>Neste del av introduksjonen kan brukes får å presentere problemet som man ønsker å undersøke eller rapportere kring. Denne delen kan sies være analytisk. I et større vitenskapelig arbeid (f.eks. en bacheloroppgave) bruker vi denne delen får å formulere forskningsspørsmål eller hypoteser basert på tidligere forskning og kunnskapshull.</p>
<p>I en større rapport kan man under introduksjonskapitlet og rapportere en mer omfattende litteraturgjennomgang.</p>
<p>Introduksjonen kan sies besvare spørsmålene: Hva er feltet? Hva er problemet? Hvorfor er det problemet?</p>
<p>Prøv å unngå å motivere dine tekster med for eksempel «Hensikten med denne teksten er å besvare oppgaven i emnet…». Unngå også å bruk plass på «I introduksjonen vil jeg presentere en introduksjon til emnet…». Begge eksemplene over kan sies være deler i din tekst som beskriver teksten, fokusere istedenfor på å beskrive fenomenet du ønsker å fortelle leseren om.</p>
</section>
<section id="metode" class="level3" data-number="10.4.2">
<h3 data-number="10.4.2" class="anchored" data-anchor-id="metode"><span class="header-section-number">10.4.2</span> Metode</h3>
<p>Under metode forventes man beskriv hvordan man gjennomfører sin studie. Denne kan beskrives som for eksempel et eksperiment, en observasjon, en litteraturgjennomgang. I en større rapport kan man fordele metodedelen over flere underkapittel som først gir en oversikt over studien følget av en detaljerte beskrivelser av hvordan forskjellige metoder har blitt gjennomført.</p>
<p>Metoden skreves i fortid, når du rapporterer på et gjennomført eksperiment eller observasjon. Beskrivelsen skall være så pass detaljert at leseren selv kan gjennomføre eksperimentet. En detaljert beskrivelse av metoden gir leseren mulighet å bedømme hvor tilforlatelige resultatene er.</p>
</section>
<section id="resultat" class="level3" data-number="10.4.3">
<h3 data-number="10.4.3" class="anchored" data-anchor-id="resultat"><span class="header-section-number">10.4.3</span> Resultat</h3>
<p>Her besvares spørsmålet om hva som ble funnet i eksperimentet, observasjonen eller litteraturgjennomgangen. Resultatene kan være meget enkle gjennom for eksempel presentasjon av et gjennomsnitt og spredningsmål av en måling, eller meget komplekse gjennom presentasjon av flere målinger fra flere eksperimenter og statistiske modeller. Resultater er ofte presenterte i tekst, tabeller og figurer. Tabeller og figurer hjelper forfatteren å presentere mye data på en strukturert måte. Figurer og tabeller forteller leseren mer på begrenset plass sammenlignet med tekst. Men i teksten må du henvise til figurer og tabeller, ingen figurer eller tabeller får være ukommenterte. Tenk på teksten i resultatdelen som et gelender som leder leseren gjennom rapporten i en logisk orden. Med hånden stadig plassert på gelenderet har leseren mulighet å skjønne hva figurer og tabeller formidler og setter disse i kontekst. Tar du vekk gelenderet faller leseren mot en sikker død i en avgrunn av enkeltstående figurer og tabeller.</p>
<p>Hvis leseren selv hopper over gelenderet og prøver å skjønne tabeller og figurer uten din trygge ledsagelse så kan du fortsatt være en god forfatter gjennom å beskrive hva figurer og tabeller viser. En regel er at figurer og tabeller bør kunne leses for seg selv. En figurtekst bør inneholde tilstrekkelig informasjon for at leseren skal ha mulighet å skjønne hva den viser. Det samme gjelder tabeller.</p>
</section>
<section id="diskusjon" class="level3" data-number="10.4.4">
<h3 data-number="10.4.4" class="anchored" data-anchor-id="diskusjon"><span class="header-section-number">10.4.4</span> Diskusjon</h3>
<p>I diskusjonen forteller du leseren hva resultatene betyr, du gjør en tolkning av resultatene som du tidligere har presentert. Tolkningen binder sammen introduksjonen, metoden og resultatene. Du bør i diskusjonen i tillegg til å fortelle om tolkningen og beskrive hvorfor du syns resultatene kan tolkes på den måte du presenterer. Du kan ytterligere balansere denne beskrivelsen gjennom å vise leseren hvordan din studie er begrenset. I diskusjonen bør du også bruke referanser og kilder får alle utsagn som ikke bygger på presentasjonen i resultatdelen. Du kan ved hjelp av tidligere forskning forklara dine resultater og sette disse i rett kontekst.</p>
<p>Din tolkning kan være feilaktig, men du bør velge et konsekvent spår som beskriver din forståelse av den data du presenterer. Du kan også presentere steg for å komme videre med et forskningsspørsmål.</p>
<p>Til sist presenterer du en konklusjon som summerer opp rapporten. I noen tekster er rapporten et eget avsnitt eller kapitel men i kortere rapporter er konklusjonen en måte å avslutte diskusjonen på.</p>
</section>
</section>
<section id="paragrafer" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="paragrafer"><span class="header-section-number">10.5</span> Paragrafer</h2>
<p>En tekst kan deles opp i mindre stykker som kan sies være verktøy for å formidle dit budskap til leseren. En viktig bestanddel i en tekst er paragrafer. En paragraf starter med en setning som beskriver paragrafens tema, emne eller hensikt. Dette kan være et utsagn som for eksempel «laks er en fisk som er nyttig å spise». Temasetning følges av en eller flere setninger som gir støtte til påstanden eller temaet for paragrafen. En støttesetning kan være «Laksen inneholder mye nyttige fettsyrer samtidig som den er proteinrik». Til sist avsluttes paragrafen med en overgangssetning som ledere leseren videre til neste paragraf. En overgangssetning kan være «Laks kan derfor være del i et sundt kosthold som bidrar til god muskelhelse sammen med andre proteinrike livsmiddel». Den siste setningen, en overgangssetning kan konkludere noe samtidig som det ledere leseren in på neste tema (muskelhelse og proteinrike livsmiddel i dette eksemplet).</p>
<p>En tekst kan gis struktur gjennom att du starter nye paragrafer når du introduserer nye temaer. Hver paragraf kan bearbeides får å gis en viss grad av selvstendighet. Dette gir deg mulighet å flytte rundt paragrafer får å gi din tekst en logisk rekkefølge. Du kan og bruke paragrafer får å begrense din tekst. Gi deg selv en begrenset plass for å formidle noe, la oss si tre paragrafer for å skrive en introduksjon. Lag en liste over hva hver paragraf skal formidle (tema), sett opp noen punkter som er til støtte for ditt tema og lag til sist et punkt som beskriver hvordan du konkluderer paragrafen og hvordan den ledere leseren videre. Du har nå strukturert dine paragrafer, og derved også din tekst.</p>



</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./05-a-intro.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Presentere og lese statistiske analyser</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./05-jamovi.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">05-jamovi.html</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>