project:
  type: book

book:
  title: "Statistisk dataanalyse med Jamovi"
  author: "Daniel Hammarström"
  date: "2024-01-02"
  chapters:
    - index.qmd
    - part: 01-a-intro.qmd
      chapters: 
      - 01-deskriptiv-dataanalyse.qmd
      - 01-jamovi.qmd
    - part: 02-a-intro.qmd
      chapters: 
      - 02-statistisk-samvariasjon.qmd
      - 02-jamovi.qmd
    - 03-kausalsammenheng.qmd
    - 04-induktiv-statistikk.qmd
    - 05-formidling.qmd
    - references.qmd

bibliography: references.bib

crossref:
  fig-title: Figur     # (default is "Figure")
  fig-prefix: Figur
  tbl-prefix: Tabell
  tbl-title: Tabell     # (default is "Table")
  title-delim: "."   # (default is ":")

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



