---
title: "Arbeidsfysiologisk metode og Statistikk"
subtitle: "Statistisk samvariasjon"
format:
  revealjs:
    include-in-header: 
      text: |
        <style>
        .center-xy {
          margin: 0;
          position: absolute;
          top: 25%;
          left: 0%;
          -ms-transform: translateY(-50%), translateX(-0%);
          transform: translateY(-50%), translateX(-0%);
        }
        </style>
    embed-resources: true
standalone: true
bibliography: present-references.bib
editor_options: 
  chunk_output_type: console
---

## Samvariasjon


```{r}
#| fig-align: "center"
#| fig-width: 7
#| fig-height: 6


library(tidyverse); library(ggthemes); library(cowplot); library(ggtext)


p1 <- data.frame(A = 10, B = 5) %>%
  pivot_longer(names_to = "Kategori", values_to = "Antall", cols = A:B) %>%
  
  ggplot(aes(Kategori, Antall)) + 
  geom_bar(stat = "identity", aes(fill = Kategori)) + 
  
  scale_y_continuous(limits = c(0, 12), expand = c(0, 0)) +
  scale_fill_manual(values = c("steelblue", "darkblue")) +
  
  theme_few(base_size = 12) + theme(legend.position = "none")
  
  
p2 <- data.frame(vo2maks = runif(100, 45, 70)) %>%
  rowwise() %>%
  
  mutate(runtime = rnorm(1, 900 - vo2maks * 5.5, 15)) %>%
  ungroup() %>%
  mutate(kmh = 3 / (runtime/3600)) %>%
 
  ggplot(aes(vo2maks, runtime)) + 
  geom_point(shape = 21, color = "steelblue") +

  labs(x = "VO<sub>2max</sub> (ml kg<sup>-1</sup> min<sup>-1</sup>)", 
       y = "3000m tid (sek)") +
  
  theme_few(base_size = 12) + theme(legend.position = "none", 
                                    axis.title.x = element_markdown(), 
                                    axis.title.y = element_markdown())


 p3 <- read.csv("data/temperature.csv") %>%
   
   separate(date, into = c("year", "month", "day"), sep = "-") %>%
   mutate(year = as.numeric(year), 
          month = as.numeric(month)) %>%
   group_by(year) %>%
   summarise(temp = mean(temp)) %>%
 
   ggplot(aes(year, temp)) + 
   
   geom_line() +
     geom_point(shape = 21, color = "darkred", size = 2) +
 
   labs(x = "&Aring;r", 
        y = "Global gjennomsnittstemperatur (&deg;C)") +
   
   theme_few(base_size = 12) + theme(legend.position = "none", 
                                     axis.title.x = element_markdown(), 
                                     axis.title.y = element_markdown())
 
 


dat <- read.csv2("data/student_trening_1_2_3.csv", header = FALSE, skip = 1) %>%
  select(sex = V7, 
         idrettslag = V5, 
         tren_senter = V4,
         age = V6, 
         train = V2)




d <- dat %>%
  select(sex, idrettslag) %>%
  mutate(idrettslag = if_else(idrettslag == "ja", 1, 0), 
         sex = if_else(sex == "kvinne", 0, 1)) 



p4 <- dat %>%
  select(sex, idrettslag) %>%
  group_by(sex, idrettslag) %>%
  summarise(n = n()) %>%
  group_by(sex) %>%
  mutate(prop = n / sum(n), 
         sign_row = if_else(sex == "kvinne", -1, 1), 
         sign_col = if_else(idrettslag == "nei", -1, 1)) %>%
  
  ggplot() + 
  geom_rect(aes(xmin = 0, 
                           xmax = sign_row * n, 
                           ymin = 0, 
                           ymax = sign_col * n, 
                           fill = paste(sex, idrettslag))) +
    geom_text(
    aes(label = paste(round(100 * prop,0),"%"),
        x = 0.5 * sign_row * n,
        y = 0.5 * sign_col * n), size = 3) +
  geom_hline(yintercept = 0) +
  geom_vline(xintercept = 0) +
  coord_equal() +
  
  scale_y_continuous(breaks = c(-50, 50), labels = c("Nei", "Ja")) +
  
  scale_x_continuous(breaks = c(-100, 50), labels = c("Kvinne", "Mann")) +
  
  labs(y = "Idrettslag", 
       x = "Kj&#248;nn") + 
  
  theme_minimal() + 
  theme(axis.title.x = element_markdown(angle = 0),
        axis.title.y = element_markdown(angle = 0),
        panel.grid = element_blank(), 
        legend.position = "none")
  



plot_grid(p1, p2, p3, p4)




```


## Samvariasjon

```{r}
#| fig-width: 4
#| fig-height: 4
#| fig-align: "center"

p2 <- data.frame(x = runif(10, 0, 100)) %>%
 
  
  mutate(y = x) %>%

 
  ggplot(aes(x, y)) + 

  labs(x = "Uavhengig variabel: x", 
       y = "Avhengig variabel: y") +
  
  theme_few(base_size = 12) + theme(legend.position = "none", 
                                    axis.title.x = element_markdown(), 
                                    axis.title.y = element_markdown())

p2 
```

## Modeller for samvariasjon 



```{r}



library(latex2exp)

p1 <- data.frame(x = runif(10, 0, 100)) %>%
 
  
  mutate(y = x) %>%

 
  ggplot(aes(x, y)) + 
  
  
  geom_segment(aes(x = 20, xend = 60, y = 20, yend = 60), color = "darkred") +
  geom_label(aes(x = 85, y = 60), label = TeX("y=0 + 1\\times x"), color = "darkred") +
  
 # geom_segment(aes(x = 20, xend = 60, y = 40, yend = 40), color = "steelblue") +
 # geom_label(aes(x = 85, y = 40), label = TeX("y=40 + 0\\times x"), color = "steelblue") +
  
 # geom_segment(aes(x = 20, xend = 60, y = 60, yend = 20), color = "darkgreen") +
 # geom_label(aes(x = 85, y = 20), label = TeX("y= 80 -1\\times x"), color = "darkgreen") +
  
  scale_y_continuous(limits = c(0, 100)) +

  scale_x_continuous(limits = c(0, 100)) +
  
  
  labs(x = "Uavhengig variabel: x", 
       y = "Avhengig variabel: y") +
  
  theme_few(base_size = 12) + theme(legend.position = "none", 
                                    axis.title.x = element_markdown(), 
                                    axis.title.y = element_markdown())


p2 <- data.frame(x = runif(10, 0, 100)) %>%
 
  
  mutate(y = x) %>%

 
  ggplot(aes(x, y)) + 
  
  
 # geom_segment(aes(x = 20, xend = 60, y = 20, yend = 60), color = "darkred") +
 # geom_label(aes(x = 85, y = 60), label = TeX("y=0 + 1\\times x"), color = "darkred") +
  
  geom_segment(aes(x = 20, xend = 60, y = 40, yend = 40), color = "steelblue") +
  geom_label(aes(x = 85, y = 40), label = TeX("y=40 + 0\\times x"), color = "steelblue") +
  
 # geom_segment(aes(x = 20, xend = 60, y = 60, yend = 20), color = "darkgreen") +
 # geom_label(aes(x = 85, y = 20), label = TeX("y= 80 -1\\times x"), color = "darkgreen") +
  
  scale_y_continuous(limits = c(0, 100)) +

  scale_x_continuous(limits = c(0, 100)) +
  
  
  labs(x = "Uavhengig variabel: x", 
       y = "Avhengig variabel: y") +
  
  theme_few(base_size = 12) + theme(legend.position = "none", 
                                    axis.title.x = element_markdown(), 
                                    axis.title.y = element_markdown())


p3 <- data.frame(x = runif(10, 0, 100)) %>%
 
  
  mutate(y = x) %>%

 
  ggplot(aes(x, y)) + 
  
  
 # geom_segment(aes(x = 20, xend = 60, y = 20, yend = 60), color = "darkred") +
 # geom_label(aes(x = 85, y = 60), label = TeX("y=0 + 1\\times x"), color = "darkred") +
  
 # geom_segment(aes(x = 20, xend = 60, y = 40, yend = 40), color = "steelblue") +
#  geom_label(aes(x = 85, y = 40), label = TeX("y=40 + 0\\times x"), color = "steelblue") +
  
  geom_segment(aes(x = 20, xend = 60, y = 60, yend = 20), color = "darkgreen") +
  geom_label(aes(x = 85, y = 20), label = TeX("y= 80 -1\\times x"), color = "darkgreen") +
  
  scale_y_continuous(limits = c(0, 100)) +

  scale_x_continuous(limits = c(0, 100)) +
  
  
  labs(x = "Uavhengig variabel: x", 
       y = "Avhengig variabel: y") +
  
  theme_few(base_size = 12) + theme(legend.position = "none", 
                                    axis.title.x = element_markdown(), 
                                    axis.title.y = element_markdown())



 
```

::: {.center-xy}

:::: {.columns}

::: {.column width="33%"}

::: {.fragment}

```{r}
#| fig-width: 3.5
#| fig-height: 3
#| fig-align: "center"

p1


```


:::



:::

::: {.column width="33%"}

::: {.fragment}
```{r}
#| fig-width: 3.5
#| fig-height: 3
#| fig-align: "center"

p2


```
:::

:::

::: {.column width="33%"}

::: {.fragment}
```{r}
#| fig-width: 3.5
#| fig-height: 3
#| fig-align: "center"

p3


```
:::

:::


::::


:::


## En modell for gjennomsnittet










